#include <stdio.h>
#include <stdlib.h>  // For rand() and srand()
#include <time.h>    // For time()

int main() {
    /*
    =====================================================================
    PSEUDO-RANDOM NUMBERS IN C - EXPLANATION INSIDE COMMENTS
    =====================================================================

    1) What are pseudo-random numbers?
       - These are numbers generated by an algorithm that simulate randomness.
       - They are NOT truly random because the sequence can be reproduced if
         you know the starting point called the "seed".
       - They are used in simulations, games, testing, and anywhere random-like
         behavior is needed.

    2) rand() function:
       - Provided by stdlib.h.
       - Generates pseudo-random integers between 0 and RAND_MAX.
       - RAND_MAX is a constant (usually 32767 or more) that limits the max number.

    3) srand() function:
       - Seeds the random number generator.
       - If you do not call srand(), rand() will generate the same sequence on every run.
       - Common practice is to seed it with current time: srand(time(NULL));
       - time(NULL) returns number of seconds elapsed since Jan 1, 1970 (Epoch).
       - Because time changes every second, this ensures different seeds on each program run.

    4) Generating numbers in a specific range:
       - rand() returns number in [0, RAND_MAX].
       - To get a number in [min, max], use:
            number = (rand() % (max - min + 1)) + min;
       - Example: number between 1 and 10:
            number = (rand() % 10) + 1;

    =====================================================================
    */

    // Seed the pseudo-random number generator with the current time
    // This ensures the sequence changes each time you run the program.
    srand(time(NULL));

    printf("Generating 5 pseudo-random numbers (0 to RAND_MAX):\n");
    for (int i = 0; i < 5; i++) {
        int randNum = rand(); // Get a pseudo-random integer
        printf("Random Number %d: %d\n", i + 1, randNum);
    }

    // Now let's generate numbers in a specific range: 1 to 100
    printf("\nGenerating 5 pseudo-random numbers between 1 and 100:\n");
    int min = 1;
    int max = 100;

    for (int i = 0; i < 5; i++) {
        // rand() % (max - min + 1) gives a number in range [0, max-min]
        // Adding min shifts range to [min, max]
        int randInRange = (rand() % (max - min + 1)) + min;
        printf("Random Number %d: %d\n", i + 1, randInRange);
    }

    /*
    Key Points to Remember:
    ----------------------------------------
    - Always call srand(time(NULL)) once before calling rand().
    - If you call srand() multiple times rapidly with the same seed (e.g. inside a loop),
      the sequence will restart and not appear random.
    - rand() returns integer values, for floating-point random numbers,
      you can normalize by dividing by RAND_MAX, e.g.:
        float f = (float)rand() / RAND_MAX; // gives a float in [0, 1]
    - For cryptographically secure random numbers, rand() and srand() are NOT suitable.
      Use system-specific secure RNGs instead.

    */

    return 0;
}
